### ISSUE TITLE
FeatureCollection の扱いについて

### ISSUE THREAD

**Issue by ubukawa** [unvt/kata#5]
お世話になります。開発ありがとうございます。
早速、kataのfilterを使ってみました！

複数のgeojsonファイルからndjsonのtippecanoe入力ファイルを作って、それをtippecanoeに入れる実験をしていたのですが、これがFeatureCollectionでラップされているので、tippecanoeにそのまま入力できません。
皆様、どのようにされていますか？？

（参考、tippecanoeのreadme　usageのところに書いてある文章）
The GeoJSON features need not be wrapped in a FeatureCollection. You can concatenate multiple GeoJSON features or files together, and it will parse out the features and ignore whatever other objects it encounters.

**Comment by hfu** [comment]
@ubukawa [tippecanoe-json-tool](https://github.com/mapbox/tippecanoe#tippecanoe-json-tool) でラップを外せたと思います。

```zsh
ogr2ogr ... | tippecanoe-json-tool | tippecanoe ...
```

というパターンはよく使っています。例えば、リンク先のような感じです。

- https://github.com/optgeo/ise/blob/491e547bad5ba826c78a44fa72e76599e40aa2d6/download.rb#L8
- https://github.com/optgeo/kengyu/blob/86be492bc577e1099230cbe9f168b199a7a39e9b/Rakefile#L16

**Comment by ubukawa** [comment]
@hfu さん、早速ありがとうございます！！　FeatureCollectionのラップを外せました！

一方で、kataのfilterで付与するtippecanoeの要素がFeatureCollecationのすぐ下のオブジェクトなので（Featuresの各オブジェクトには定義されていない）、ラップを外すとtippecanoe用のmaxzoomとminzoomが消えてしまいました。tippecanoe-json-toolの-eオプションを試しましたがうまくいかず。。。

（filterのソースを見ながら、そもそもfilterするまえのgeojsonからラップを外してみたらなどと想像したので、もう少し実験してみます。）

**Comment by ubukawa** [comment]
For reference, two types of files are stored in https://github.com/ubukawa/kata-test .
(with or without tippecanoe-json-tool, or FeatureCollection wrapping. see the following command)

```
root@7fe761f09710:/data# kata filter ./kata.yml | tippecanoe-json-tool > compiled.geojson
root@7fe761f09710:/data# kata filter ./kata.yml > compiled0.geojson
```

**Comment by ubukawa** [comment]
ありがとうございます。#7の方に引き継がれましたのでこちらは閉じます。ありがとうございました。
