### ISSUE TITLE
layer nameの指定について

### ISSUE THREAD

**Issue by ubukawa** [unvt/kata#6]
filterの機能を早速試させていただいています！ありがとうございます。

複数のgeojsonファイルをフィルターするとき、ベクトルタイルのレイヤ名はどうやって指定できるでしょうか？
minzoomとmaxzoomはkata.ymlで指定できますが、layerをkata.tmlに追加してもtippecanoeのプロパティには反映されません。

もともとのgeojsonのファイル名が反映されるかなと思って実験したのですが、一つの入力ファイルなので一つのレイヤとして処理されてしまっているようです。
![image](https://user-images.githubusercontent.com/59204379/161153847-14791bdd-9905-4e17-ac4a-15178709c9ca.png)

私の使い方がそもそも間違っていたらすみませんが、何かご経験があれば教えていただけると大変幸いです！

（参考）
https://speakerdeck.com/hfu/unvtwakusiyotupu-ri-ben-yu-ban?slide=26

**Comment by ubukawa** [comment]
ベクトルタイルのレイヤ名もyamlで指定できるように少し考えてみました。
私自身はコーディングが得意でないのですが、このような追加が可能かどなたかご確認いただけないでしょうか？
https://github.com/unvt/kata/blob/add-layer4tippecanoe/src/command/filter.ts#L52-L55

（ただし、tippecanoe.minzoom、tippecanoe.maxzoom、tippecanoe.layerともに、入力ファイルがFeatureCollectionになっていると、tippecanoeがFeatureCollectionの直下のオブジェクトになってしまい、各地物にはtippecanoe情報が入らないのでベクトルタイル変換の時にまだうまくいきません。）

**Comment by hfu** [comment]
This is closely related to #7.

**Comment by ubukawa** [comment]
This has been revised in the context of #7. So, I close here. Thank you, all!!!
