### ISSUE TITLE
`minzoom` and `maxzoom` in YAML doesn't work as expected

### ISSUE THREAD

**Issue by miya0001** [unvt/kata#7]
The `tippecanoe` property should be moved from GeoJSON root to each feature's root?

Related: #5

**Comment by hfu** [comment]
Thanks, @miya0001!

As documented in https://github.com/mapbox/tippecanoe#geojson-extension, `tippecanoe` property should be a property of a `Feature`. 

`maxzoom`, `minzoom`, and `layer` are documented properties of the `tippecanoe` property.

I think `kata` can simply pass a given object without checking its content.

**Comment by ubukawa** [comment]
Dear @miya0001  and @hfu ,

Greetings! I failed to install kata v1.0.3 in docker and found that npm may not be published yet due to some error.
https://github.com/unvt/kata/runs/5814451617?check_suite_focus=true

Could you kindly confirm it? Thank you!

**Comment by ubukawa** [comment]
コードについてはまだ初心者の域を出られないので見当違いでしたら恐縮ですが、publish npmの際のエラーで、 src/lib/interfaces.ts(1,25): error TS2307: Cannot find module 'GeoJSON' or its corresponding type declarations. というメッセージが出ているところをみると、
https://github.com/unvt/kata/blob/main/src/lib/interfaces.ts#L1 でGeoJSONではなくてgeojsonと小文字で定義した方が良いのでしょうか？（package.jsonをみるとdevDependenciesで types/geojson と小文字で定義されています。）

※ただし、小文字でgeojsonにするとcommand/filter.tsの中でもlet geojson を定義しているので(forループのなかですが)、重複しないか少し気になりました。

Reviewの時に気がつかなくてすみませんでしたが、 @miya0001 さんにご確認いただけると幸いです。よろしくお願いします。

**Comment by ubukawa** [comment]
I have confirmed the cause of the error.
By changing the "GeoJSON" to "geojson", the tool works fine.

![2022-04-11-kata](https://user-images.githubusercontent.com/59204379/162804693-95be5a55-53ae-4a50-8b3c-16c980c99ceb.png)

![2022-04-11-kata2](https://user-images.githubusercontent.com/59204379/162805240-6a678bb6-7c03-4973-8d23-b2c16697a8dc.png)

I will make a pull request.

**Comment by ubukawa** [comment]
Thank you!
